using System;
using MirraCloud.Core.Enums;

namespace MirraCloud.Core.Auth
{
    public class PlayerAccountInfo
    {
        public string Id { get; private set; }
        public string ScopeId { get; private set; }

        /// <summary>Base nickname the player typed (without any random suffix).</summary>
        public string NicknameBase { get; private set; }
        /// <summary>Random suffix generated by the server, or null when not active.</summary>
        public string NicknameSuffix { get; private set; }
        /// <summary>Server-composed display nickname (Base or Base+Suffix). Use this for UI.</summary>
        public string Nickname { get; set; }

        /// <summary>Mutable, project-unique public handle (stored with the acc_ prefix).</summary>
        public string Username { get; set; }
        public Gender Gender { get; set; }

        public int Age { get; private set; }
        public IconKeyDto IconKey { get; private set; }
        /// <summary>Public Dicebear avatar URL when the account uses a Dicebear preset; null otherwise.</summary>
        public string AvatarUrl { get; private set; }
        public CountryCode Country { get; private set; }
        public LanguageCode LanguageCode { get; private set; }
        public string TimeZone { get; private set; }
        public string Status { get; private set; }
        public string[] SegmentKeys { get; private set; }
        public string[] AbTestKeys { get; private set; }
        public DateTime CreatedDate { get; private set; }
        public DateTime UpdatedDate { get; private set; }
        public DateTime LastLoginDate { get; private set; }

        public int TotalActiveDays { get; private set; }
        public int ConsecutiveActiveDays { get; private set; }
        public int MaxConsecutiveActiveDays { get; private set; }
        public int TotalSessions { get; private set; }

        public PlayerAccountInfo(AccountDto dto)
        {
            if (dto == null)
            {
                throw new ArgumentNullException(nameof(dto));
            }

            Id = dto.Id;
            ScopeId = dto.ScopeId;
            NicknameBase = dto.Nickname?.Base;
            NicknameSuffix = dto.Nickname?.Suffix;
            Nickname = dto.Nickname?.Displayed ?? dto.Nickname?.Base;
            Username = dto.Username;
            Gender = dto.Gender;
            Age = dto.Age;
            IconKey = dto.IconKey;
            AvatarUrl = dto.AvatarUrl;
            Country = dto.Country;
            LanguageCode = dto.LanguageCode;
            TimeZone = dto.TimeZone;
            Status = dto.Status;
            SegmentKeys = dto.SegmentKeys ?? Array.Empty<string>();
            AbTestKeys = dto.AbTestKeys ?? Array.Empty<string>();
            CreatedDate = dto.CreatedDate;
            UpdatedDate = dto.UpdatedDate;
            LastLoginDate = dto.LastLoginDate;
            TotalActiveDays = dto.TotalActiveDays;
            ConsecutiveActiveDays = dto.ConsecutiveActiveDays;
            MaxConsecutiveActiveDays = dto.MaxConsecutiveActiveDays;
            TotalSessions = dto.TotalSessions;
        }
    }
}
